In [4]:
# groupby
import pandas as pd

df = pd.DataFrame({
    'user_id': ['U1', 'U1', 'U2', 'U2', 'U3', 'U3', 'U1'],
    'amount': [100, 200, 50, 75, 300, 250, 150],
    'merchant': ['Amazon', 'Walmart', 'Amazon', 'Apple', 'Walmart', 'Amazon', 'Apple'],
    'is_fraud': [0, 0, 0, 1, 0, 0, 1]
})
df.head()

  user_id  amount merchant  is_fraud
0      U1     100   Amazon         0
1      U1     200  Walmart         0
2      U2      50   Amazon         0
3      U2      75    Apple         1
4      U3     300  Walmart         0

In [5]:
# basic groupby : sum per user
df.groupby('user_id')['amount'].sum()

user_id
U1    450
U2    125
U3    550
Name: amount, dtype: int64

In [6]:
df.groupby('user_id')['merchant'].value_counts()

user_id  merchant
U1       Amazon      1
         Walmart     1
         Apple       1
U2       Amazon      1
         Apple       1
U3       Walmart     1
         Amazon      1
Name: count, dtype: int64

In [7]:
df.stats = df.groupby('user_id').agg(
    total_spent= ('amount', 'sum'),
    avg_spent=('amount', 'mean'),
    txn_count=('amount', 'count'),
    max_txn=('amount', 'max'),
    fraud_count=('is_fraud', 'sum')
)
df.stats

C:\Users\user\AppData\Local\Temp\ipykernel_24116\345935390.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.stats = df.groupby('user_id').agg(

         total_spent  avg_spent  txn_count  max_txn  fraud_count
user_id
U1               450      150.0          3      200            1
U2               125       62.5          2       75            1
U3               550      275.0          2      300            0

In [8]:
df_columns = df.groupby(['user_id', 'merchant'])['amount'].sum()
df_columns

user_id  merchant
U1       Amazon      100
         Apple       150
         Walmart     200
U2       Amazon       50
         Apple        75
U3       Amazon      250
         Walmart     300
Name: amount, dtype: int64

In [9]:
# transform
df_transform = df.groupby('user_id')['amount'].transform('mean')
df_transform

0    150.0
1    150.0
2     62.5
3     62.5
4    275.0
5    275.0
6    150.0
Name: amount, dtype: float64

In [10]:
df_fraud = df.groupby('user_id')['is_fraud'].sum()
df_fraud

user_id
U1    1
U2    1
U3    0
Name: is_fraud, dtype: int64