In [2]:
import pandas as pd

customers = pd.DataFrame({
    'user_id': ['U1', 'U2', 'U3'],
    'name': ['Alice', 'Bob', 'Carol'],
    'age': [30, 45, 28]
})

transactions = pd.DataFrame({
    'user_id': ['U1', 'U1', 'U2', 'U4'],
    'amount': [100, 200, 50, 300]
})

In [3]:
transactions

  user_id  amount
0      U1     100
1      U1     200
2      U2      50
3      U4     300

In [4]:
df_merged = pd.merge(customers, transactions, on='user_id', how='inner')
df_merged

  user_id   name  age  amount
0      U1  Alice   30     100
1      U1  Alice   30     200
2      U2    Bob   45      50

In [6]:
# left join
df_merged_left = pd.merge(customers, transactions, on = 'user_id', how='left')
df_merged_left

  user_id   name  age  amount
0      U1  Alice   30   100.0
1      U1  Alice   30   200.0
2      U2    Bob   45    50.0
3      U3  Carol   28     NaN

In [7]:
df_merged_outer= pd.merge(customers, transactions, on='user_id', how='outer')
df_merged_outer

  user_id   name   age  amount
0      U1  Alice  30.0   100.0
1      U1  Alice  30.0   200.0
2      U2    Bob  45.0    50.0
3      U3  Carol  28.0     NaN
4      U4    NaN   NaN   300.0

In [12]:
df_merged_diff = pd.merge(customers, transactions, left_on='user_id', right_on='user_id')
df_merged_diff

  user_id   name  age  amount
0      U1  Alice   30     100
1      U1  Alice   30     200
2      U2    Bob   45      50