In [13]:
import pandas as pd
df = pd.DataFrame({
    'date': pd.date_range('2024-01-01', periods=10),
    'sales': [100, 120, 90, 150, 200, 180, 110, 95, 220, 175]
})

df['rolling_mean_3'] = df['sales'].rolling(window=3).mean()
df['rolling_std_3'] = df['sales'].rolling(window=3).std()
df['rolling_max_3'] = df['sales'].rolling(window=3).max()
df

        date  sales  rolling_mean_3  rolling_std_3  rolling_max_3
0 2024-01-01    100             NaN            NaN            NaN
1 2024-01-02    120             NaN            NaN            NaN
2 2024-01-03     90      103.333333      15.275252          120.0
3 2024-01-04    150      120.000000      30.000000          150.0
4 2024-01-05    200      146.666667      55.075705          200.0
5 2024-01-06    180      176.666667      25.166115          200.0
6 2024-01-07    110      163.333333      47.258156          200.0
7 2024-01-08     95      128.333333      45.368859          180.0
8 2024-01-09    220      141.666667      68.251984          220.0
9 2024-01-10    175      163.333333      63.311400          220.0

In [5]:
df['rolling_mean_3']

0           NaN
1           NaN
2    103.333333
3    120.000000
4    146.666667
5    176.666667
6    163.333333
7    128.333333
8    141.666667
9    163.333333
Name: rolling_mean_3, dtype: float64

In [6]:
df['rolling_std_3']

0          NaN
1          NaN
2    15.275252
3    30.000000
4    55.075705
5    25.166115
6    47.258156
7    45.368859
8    68.251984
9    63.311400
Name: rolling_std_3, dtype: float64

In [7]:
df['rolling_max_3']

0      NaN
1      NaN
2    120.0
3    150.0
4    200.0
5    200.0
6    200.0
7    180.0
8    220.0
9    220.0
Name: rolling_max_3, dtype: float64

In [16]:
import pandas as pd

df = pd.DataFrame({
    'user_id': ['U1', 'U1', 'U2', 'U2', 'U3', 'U3', 'U1'],
    'timestamp': pd.date_range('2024-01-01', periods=7),
    'amount': [100, 200, 50, 75, 300, 250, 150],
    'merchant': ['Amazon', 'Walmart', 'Amazon', 'Apple', 'Walmart', 'Amazon', 'Apple'],
    'is_fraud': [0, 0, 0, 1, 0, 0, 1]
})

df = df.sort_values(['user_id', 'timestamp'])

df['user_rolling_avg'] = (
    df.groupby('user_id')['amount']
      .rolling(window=3, min_periods=1)
      .mean()
      .reset_index(level=0, drop=True)
)

df

  user_id  timestamp  amount merchant  is_fraud  user_rolling_avg
0      U1 2024-01-01     100   Amazon         0             100.0
1      U1 2024-01-02     200  Walmart         0             150.0
6      U1 2024-01-07     150    Apple         1             150.0
2      U2 2024-01-03      50   Amazon         0              50.0
3      U2 2024-01-04      75    Apple         1              62.5
4      U3 2024-01-05     300  Walmart         0             300.0
5      U3 2024-01-06     250   Amazon         0             275.0

In [18]:
df['amount_rolling_sum_7'] = df['amount'].rolling(window=7, min_periods=1).sum()
df['amount_rolling_q95_30'] = df['amount'].rolling(window=30, min_periods=1).quantile(0.95)

df_time = df.sort_values('timestamp').set_index('timestamp')
df_time['amount_rolling_mean_7d'] = df_time['amount'].rolling('7D').mean()

df_time

,user_id,amount,merchant,is_fraud,user_rolling_avg,amount_rolling_sum_7,amount_rolling_q95_30,amount_rolling_mean_7d
timestamp,,,,,,,,
2024-01-01,U1,100,Amazon,0,100.0,100.0,100.0,100.000000
2024-01-02,U1,200,Walmart,0,150.0,300.0,195.0,150.000000
2024-01-03,U2,50,Amazon,0,50.0,500.0,192.5,116.666667
2024-01-04,U2,75,Apple,1,62.5,575.0,190.0,106.250000
2024-01-05,U3,300,Walmart,0,300.0,875.0,275.0,145.000000
2024-01-06,U3,250,Amazon,0,275.0,1125.0,285.0,162.500000
2024-01-07,U1,150,Apple,1,150.0,450.0,195.0,160.714286